//  NPM INSTALL _____ -E 
//  NPM INSTALL _____ --SAVE-DEV   >> PARA DEIXAR EM DEPENDENCIA DE DESENVOLVIMENTO 
//  NPM INSTALL _____ --SAVE-PROD  >> PARA DEIXAR EM DEPENDENCIA DE PRODUCAO 
//  NPM UNINSTAL _____
//  NPM LS  >> PARA LISTAR AS DEPENDENCIAS | NPM LS --DEPTH=0  >> PARA LISTAR A PROFUNDIDADE DAS DEPENDENCIAS
//  NPM OUTDATED  >> PARA LISTAR AS VERSOES DESATUALIZADAS 
